import { StyleSheet } from 'react-native'

export const setIncomeModalStyles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.65)',
    justifyContent: 'flex-end',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
  },
  container: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheet: {
    flex: 1,
    overflow: 'hidden',
  },
  sheetGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  sheetContent: {
    paddingTop: 18,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    marginBottom: 24,
  },
  headerSpacer: {
    width: 20,
  },
  title: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 18,
    fontWeight: '700',
  },
  content: {
    paddingHorizontal: 24,
  },
  section: {
    marginBottom: 18,
  },
  label: {
    color: 'rgba(255,255,255,0.2)',
    fontSize: 8,
    letterSpacing: 2,
    marginBottom: 8,
  },
  hint: {
    color: 'rgba(255,255,255,0.3)',
    fontSize: 12,
    marginBottom: 10,
    lineHeight: 17,
  },
  selectRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 14,
    padding: 14,
  },
  selectIcon: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(94,189,151,0.25)',
    backgroundColor: 'rgba(94,189,151,0.12)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectText: {
    flex: 1,
    color: 'rgba(255,255,255,0.8)',
    fontSize: 14,
    fontWeight: '600',
  },
  placeholderText: {
    flex: 1,
    color: 'rgba(255,255,255,0.4)',
    fontSize: 14,
  },
  input: {
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 12,
    padding: 14,
    color: 'rgba(255,255,255,0.85)',
    fontSize: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  amountRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'stretch',
  },
  amountInput: {
    flex: 1,
  },
  currencyPill: {
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  currencyText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 13,
    fontWeight: '700',
  },
  paidPill: {
    minWidth: 88,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    borderRadius: 12,
    paddingHorizontal: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paidText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 11,
    fontWeight: '700',
    marginBottom: 4,
  },
  inputError: {
    borderColor: 'rgba(201,107,107,0.9)',
  },
  errorText: {
    fontSize: 12,
    color: 'rgba(201,107,107,0.9)',
    marginTop: 4,
  },
  dateRow: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'stretch',
  },
  dateField: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inlineField: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  dateText: {
    color: 'rgba(255,255,255,0.7)',
    fontSize: 14,
  },
  todayPill: {
    backgroundColor: 'rgba(91,163,201,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(91,163,201,0.3)',
    borderRadius: 12,
    paddingHorizontal: 16,
    justifyContent: 'center',
  },
  todayText: {
    color: 'rgba(91,163,201,0.9)',
    fontSize: 13,
    fontWeight: '700',
  },
  moreToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    marginBottom: 18,
  },
  moreToggleText: {
    color: 'rgba(92,163,255,0.92)',
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  multilineInput: {
    minHeight: 92,
    textAlignVertical: 'top',
  },
  toggleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.07)',
  },
  toggleTextWrap: {
    flex: 1,
  },
  toggleTitle: {
    color: 'rgba(255,255,255,0.82)',
    fontSize: 14,
    fontWeight: '700',
  },
  toggleHint: {
    color: 'rgba(255,255,255,0.34)',
    fontSize: 11,
    marginTop: 4,
    lineHeight: 16,
  },
  errorBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(201,107,107,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(201,107,107,0.22)',
    borderRadius: 12,
    padding: 12,
    marginTop: 4,
  },
  errorBoxText: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.7)',
    flex: 1,
  },
  footer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
    paddingHorizontal: 24,
  },
  cancelButton: {
    flex: 1,
    padding: 16,
    alignItems: 'center',
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.04)',
  },
  cancelButtonText: {
    color: 'rgba(255,255,255,0.4)',
    fontWeight: '700',
  },
  submitButton: {
    flex: 2,
    borderRadius: 14,
    overflow: 'hidden',
  },
  submitGradient: {
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitButtonText: {
    color: '#0a0a0e',
    fontWeight: '700',
  },
  categoryOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'flex-end',
    zIndex: 99,
  },
  categoryBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  categorySheet: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    overflow: 'hidden',
    maxHeight: '60%',
  },
  categoryHandleArea: {
    alignItems: 'center',
    paddingTop: 12,
    paddingBottom: 4,
  },
  categoryContent: {
    paddingHorizontal: 24,
    paddingBottom: 36,
  },
  categoryTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    marginTop: 8,
  },
  categoryTitle: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: 17,
    fontWeight: '700',
  },
  editPill: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
  },
  editPillText: {
    color: 'rgba(255,255,255,0.5)',
    fontSize: 12,
    fontWeight: '600',
  },
  categoryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    paddingVertical: 13,
  },
  categoryRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.05)',
  },
  categoryRowIcon: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryRowLabel: {
    flex: 1,
    color: 'rgba(255,255,255,0.78)',
    fontSize: 14,
    fontWeight: '600',
  },
})
